### ISSUE TITLE
Connections Not Being Closed?

### ISSUE THREAD

**Issue by nathanashton** [mantasaudickas/NLog.Gelf#1]
Great package that does exactly what I'm after, so thank you!.

It does seem though that the connections to GrayLog aren't being closed? Im running a test console project and GrayLog is showing 101 connections and climbing. Should the Write method be creating a new GelfSender every time?

**Comment by mantasaudickas** [comment]
Thank you for your comment.
Indeed it looks like a bug. I made a fix and created updated package. This time its marked as beta as NLog dependency is still not released.
You can install it using command: Install-Package NLog.Gelf -Pre
Let me know if you still have issues.
