### ISSUE TITLE
Wrong LogLevel codes

### ISSUE THREAD

**Issue by mersadk** [mantasaudickas/NLog.Gelf#2]
When sending logs to server, wrong log level code is sent. It send log level code from NLog but GrayLog uses syslog's codes. Basically those are reverse.

If you look at http://docs.graylog.org/en/2.2/pages/gelf.html for field **level** it says "_the level equal to the standard syslog levels;_"

NLog levels can be viewed here: https://github.com/NLog/NLog/blob/master/src/NLog/LogLevel.cs
Syslog levels: https://en.wikipedia.org/wiki/Syslog#Severity_level

As you can see on this image, levelName and severity doesn't match.
![4193609dd09fe0896aa32d7e6fcffa97](https://cloud.githubusercontent.com/assets/137991/25483070/9c5e1456-2b54-11e7-9edb-2768e2c1ead7.jpg)

**Comment by mantasaudickas** [comment]
Yes, you are right here. I can do a fix which will map NLog levels Trace, Debug, Info to Notice; Warn - Warning; Error - Error; Fatal - Emergency.
Other option would be just reverse order.. but semantic meaning of Nlog levels and syslog levels are quite different.

**Comment by mersadk** [comment]
I think it would be better to create mapper than to reverse order. Thanks.

**Comment by mantasaudickas** [comment]
I have updated library to version 1.1.1-rtm-beta4.
It also was changed to .netstandard1.3 instead of NetCoreApp.

**Comment by mantasaudickas** [comment]
Mappings now are as follows:
Trace = SyslogSeverity.Informational
Debug = SyslogSeverity.Debug
Info = SyslogSeverity.Notice
Warn = SyslogSeverity.Warning
Error = SyslogSeverity.Error
Fatal = SyslogSeverity.Alert

**Comment by mersadk** [comment]
I've been using this for a while and this notice level is bothering me more than it should.
Basically Notice and Info are not same, Notice is more severe. 

Before this package, I've been using [NLog.Targets.Gelf](https://github.com/travelrepublic/NLog.Targets.Gelf) for sending logs over UDP and it uses different approach for this mapper. It merges Trace and Debug from NLog into SysLog.Debug. I think that it has more sense because Trace and Debug are basically same.

Code for it's mapper can be found here (I don't agree with using Emergency instead of Alert):
https://github.com/travelrepublic/NLog.Targets.Gelf/blob/master/NLog.Target.Gelf/LogLevelExtension.cs

I you agree, I will change this as well.

**Comment by mantasaudickas** [comment]
Yep, change it. I will merge it than.

**Comment by mersadk** [comment]
Done

**Comment by mantasaudickas** [comment]
Thanks, I will check it in few hours and create updated package.

**Comment by mantasaudickas** [comment]
I was investigating a bit more about NLog to SysLog mapping and found this:
https://github.com/graffen/NLog.Targets.Syslog/blob/master/src/NLog.Targets.Syslog/MessageCreation/Severity.cs

LogLevelToSeverity = new Dictionary<LogLevel, Severity>
{
      { LogLevel.Fatal, Emergency },
      { LogLevel.Error, Error },
      { LogLevel.Warn, Warning },
      { LogLevel.Info, Informational },
      { LogLevel.Debug, Debug },
      { LogLevel.Trace, Notice }
};


seems a bit more right actually.. :)
what do you think?

**Comment by mantasaudickas** [comment]
However here: http://www.kiwisyslog.com/help/syslog/index.html?protocol_levels.htm
It is mentioned this:
"Recommended practice is to use the Notice or Informational level for normal messages."
So probably your change is fine.

**Comment by mantasaudickas** [comment]
New package created: https://www.nuget.org/packages/NLog.Gelf/1.1.2-rtm-beta4
