### ISSUE TITLE
NuGet for .NET Framework 4.5.1

### ISSUE THREAD

**Issue by mersadk** [mantasaudickas/NLog.Gelf#3]
Is it possible to make NuGet package for .NET Framework 4.5.1?

**Comment by mantasaudickas** [comment]
I don't see any reason why not.

**Comment by mersadk** [comment]
I would appreciate if you try to do it, because I have and older app where I need to use this NuGet.

**Comment by mantasaudickas** [comment]
Maybe you can do changes and make a pull request?

**Comment by mersadk** [comment]
Ok, I'll try and let you know how it goes.

**Comment by mersadk** [comment]
I've fixed it and made a pull request.
I didn't change description and version for NuGet package.

**Comment by mantasaudickas** [comment]
Package upgraded to https://www.nuget.org/packages/NLog.Gelf/1.1.2-rtm-beta4
