### ISSUE TITLE
Custom fields not sent to Graylog

### ISSUE THREAD

**Issue by mersadk** [mantasaudickas/NLog.Gelf#8]
Custom fields specified as LogEventInfo.Properties are not sent to server. They are not mapped to GelfMessage.Fields.

I've fixed it and created pull request.

@mantasaudickas Can you publish new nuget?

**Comment by mantasaudickas** [comment]
Thanks for pull request. Merged and created a new package.
https://www.nuget.org/packages/NLog.Gelf/1.1.2
