### ISSUE TITLE
Check LogEventInfo.Properties.Count != 0

### ISSUE THREAD

**Issue by snakefoot** [mantasaudickas/NLog.Gelf#9]
https://github.com/mantasaudickas/NLog.Gelf/blob/91c29d8103a000e153f948169b1fd02f50b6f5f8/src/NLog.Gelf/Targets/GelfBaseTarget.cs#L58

Reduce allocations by having this check:

`if (logEventInfo.Properties != null && logEventInfo.Properties.Count > 0)`

**Comment by mantasaudickas** [comment]
Implemented fix, released package 1.1.3.
